backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"

locale: 'pl'

collections:
  - name: "index"
    label: "Strona główna"
    files:
      - label: "Hero sekcja"
        name: "hero"
        file: "index.njk"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Nagłówek", name: "hero_heading", widget: "string" }
          - { label: "Opis", name: "hero_description", widget: "text" }
          - { label: "Tekst przycisku", name: "cta_text", widget: "string" }

  - name: "pages"
    label: "Podstrony"
    files:
      - label: "O nas"
        name: "about"
        file: "about.md"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Treść", name: "body", widget: "markdown" }
      - label: "Oferta"
        name: "oferta"
        file: "oferta.md"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Treść", name: "body", widget: "markdown" }
      - label: "Projekty"
        name: "projekty"
        file: "projekty.md"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Treść", name: "body", widget: "markdown" }
      - label: "Kontakt"
        name: "kontakt"
        file: "kontakt.md"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Treść", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Treść", name: "body", widget: "markdown" }
